### ISSUE TITLE
How to choose a model?(pb file)

### ISSUE THREAD

**Issue by ytliang97** [AISangam/Facenet-Real-time-face-recognition-using-deep-learning-Tensorflow#2]
Hi, I'm trying to use your code. But I stocked at "Training of Model" step. I don't know what model I can choose to put it inside the folder named as “model”. If I want to use other's cnn model for this, would I need to check the input size and bench to fit the pre_img?

**Comment by SaddamBInSyed** [comment]
@peshmerge  Thanks for the clarification

**Comment by ytliang97** [comment]
@peshmerge Thank you!
